### ISSUE TITLE
example "xlsx2adoc"

### ISSUE THREAD

**Issue by mschnell1** [MortalreminderPT/edit-xlsx#10]
I'm going to provide same...
Issue to be linked to appropriate merge request.

**Comment by mschnell1** [comment]
I tried to use VSCode to publish a branch I locally created. 
It suggested to create a fork. I followed the instructions but failed by "fatal: unable to access 'https://github.com/MortalreminderPT/edit-xlsx/': The requested URL returned error: 403"

**Comment by MortalreminderPT** [comment]
I think this [answer](https://github.com/trilbymedia/grav-plugin-git-sync/issues/39#issuecomment-517804081) will help you

**Comment by MortalreminderPT** [comment]
I've already see your pull request and can process it, but you'll need to fine-tune the code a bit based on my reply in #11 to pass the workflow

**Comment by mschnell1** [comment]
> I you'll need to fine-tune the code a bit based on my reply in #11 to pass the workflow
Yep I do know it's not functional right now due to several issues. 
I'll mark the pull "ready" when it is...

**Comment by mschnell1** [comment]
To go on working on the example I did a new fork and used the 0.4 branch

After doing the necessary modoficati9ns to get it running, I git this runtime message:

```
edit-xlsx ./tests/xlsx/accounting.xlsx -> ./tests/xlsx/accounting.adoc
Rows 158 -> ? ( 14 )
Row 0 (14)
thread 'main' panicked at C:\Users\Michael Schnell\rusttest\edit-xlsx\src\api\worksheet\read.rs:36:62:
```

**Comment by MortalreminderPT** [comment]
Relax, this is because I'm modifying the structure of SharedStrings to support rich text reading.

**Comment by mschnell1** [comment]
Testing ASAP...

**Comment by mschnell1** [comment]
Pushed an updated of the example onto the fork. 
You might want to test and to merge it.
Now I am going to work on colors ...
is using branch dev-04 in the fork OK ?

**Comment by MortalreminderPT** [comment]
> @MortalreminderPT 
> Pushed an update of the example onto the fork. 
> You might want to test and to merge it.
> Now I am going to work on colors ...
> is using branch dev-04 in the fork OK ? 

Yep. 
However, I've been caught up in life lately, so I may not be able to answer right away if you run into an issue during the process.😿

**Comment by mschnell1** [comment]
OK. I will continue to improve the code....

In fact (locally) text colors do work (kind of, as the way adoc handles colors is rather limited), Trying background colors today. 

I) do need you help with issue #11, though...

**Comment by mschnell1** [comment]
@MortalreminderPT 
I am rather happy with the colors

RGB: works well

Theme: in my examples I find Them 0 and Theme 1 the parameter seems to be a value. sometimes 0 ... 1 and sometimes -1 ... 1
When I use the absolute if same as gray it kind of works.
is there any description about how themes are to be handled ? 

Index: I only see index colors in the specification of the background of the background, which I don't use, yet.

**Comment by MortalreminderPT** [comment]
> Yesterday I updated the adoc example code to a rather workable version. 
> I got a lot more working on the local project. 
> But I can't support the adoc example any more, as I split the code in multiple files top make it manageable. 

Anyway, congratulations😉
