### ISSUE TITLE
when color change within text -> panic

### ISSUE THREAD

**Issue by mschnell1** [MortalreminderPT/edit-xlsx#14]
`unwrap`   `None `
in edit-xlsx\src\xml\worksheet\sheet_data\cell\inline_string.rs:45:39

**Comment by MortalreminderPT** [comment]
> `unwrap`   `None `
> in edit-xlsx\src\xml\worksheet\sheet_data\cell\inline_string.rs:45:39

Can you tell me more about it, error messages or codes that cause panic?

**Comment by mschnell1** [comment]
It happened when I define a color to some characters in the text in a cell, that (supposedly) otherwise is default.
If you can't easily reproduce it, I'll take another look on Monday

**Comment by mschnell1** [comment]
@MortalreminderPT 
Posting this in an Issue with "color" in its name:
I did mention that RGB works fine for me 
In my example "Themes" also works, but I just guessed what the values (seemingly an integer index and a fade ranging -1.0 ... 1.0) might indicate. 
Is there any documentation on color themes and any additional information for the used themes to be extracted from the library ?

**Comment by mschnell1** [comment]
BTW.: Rich text still seems to panic in the library without me being able to create an error message.

**Comment by mschnell1** [comment]
Works !
Thanks !

**Comment by mschnell1** [comment]
@MortalreminderPT 
Hmmmm. 
Trying to get the Rich text content ....

Again I cam Pretty Print it,  but the type `RichText` seems to be buried in the privat `api ` module and not accessible from the user software
