### ISSUE TITLE
text alignemt in cell

### ISSUE THREAD

**Issue by mschnell1** [MortalreminderPT/edit-xlsx#15]
left / center  / right
(Even if I don't know right now it this is supported by ADOC.)

**Comment by MortalreminderPT** [comment]
I just added the feature and tested it in [test_read_cell](https://github.com/MortalreminderPT/edit-xlsx/blob/48bcb73dfb0dee5a4ae12000c0bdf825011400fc/tests/test_read_cell.rs). It seems to work well.

**Comment by mschnell1** [comment]
Great !
Looking forward to Testing tomorrow !

**Comment by mschnell1** [comment]
I can confirm that this works perfectly in my examples.
