### ISSUE TITLE
Implement std::error::Error for error types

### ISSUE THREAD

**Issue by FlixCoder** [MortalreminderPT/edit-xlsx#19]
Thank you for the work on this crate, it looks nice!

I noticed that the error types do not implement `std::error::Error`, so they cannot be used in standard error handling and not conveniently converted to other errors.

**Comment by MortalreminderPT** [comment]
Thanks for the suggestion, I'll fix it in the future😃

**Comment by MortalreminderPT** [comment]
I implemented it in a new commit, you can see the corresponding test by clicking [here](https://github.com/MortalreminderPT/edit-xlsx/blob/36583a0edcb222123ea36aa8b2e091a9bc44a806/tests/test_error.rs#L7)

**Comment by FlixCoder** [comment]
Thanks!

**Comment by MortalreminderPT** [comment]
> Thanks!

Thanks for the suggestion, if you encounter problems using the feature, you can reopen the issue😊
