### ISSUE TITLE
RichText can only be constructed, but not read

### ISSUE THREAD

**Issue by FlixCoder** [MortalreminderPT/edit-xlsx#20]
When reading cells with rich text formatting, one can not retrieve the value as it seems. Maybe I am missing something?

**Comment by MortalreminderPT** [comment]
This is because rich text is stored differently from normal text, the content of rich text is not stored in value. Therefore it is (temporarily) unreadable

**Comment by MortalreminderPT** [comment]
Can you read rich text content using the following method?
I did a simple test and it worked in my test
```rust
let workbook = Workbook::from_path("tests/xlsx/rich-text.xlsx")?;
let worksheet = workbook.get_worksheet(1)?;
let cell = worksheet.read_cell("A1")?;
let rt = cell.rich_text.unwrap();
println!("{:?}", rt);
```

**Comment by FlixCoder** [comment]
Yes I tested that previously and it works. But there is only the Debug impl, no method to retrieve the values and formats ^^

**Comment by mschnell1** [comment]
BTW I can "pretty print" Rich text by
```        if let Some(rt) = cell_content.rich_text {
            let s = format!(
                "Rich Text not implemented: row {}, column {} content:\n{:?}",
                row + 1,
                col + 1,
                rt
            );
...
```
But the `RichText  `type (result of `cell_content.rich_text()` ) is not available, because the `words ` element is not public.

**Comment by MortalreminderPT** [comment]
> @MortalreminderPT 
> any news ? 

Yes, I see the problem. I'll fix it later.

**Comment by MortalreminderPT** [comment]
You can try reading rich text and its words with the [new test case](https://github.com/MortalreminderPT/edit-xlsx/blob/f8e47e04a073474afd1dfc1b353ebc2f53e82b7b/tests/test_rich_text.rs#L32)

**Comment by mschnell1** [comment]
Thanks, 
witjh 0.4.5 it works
